### ISSUE TITLE
ShutdownHook: NoClassDefFoundError

### ISSUE THREAD

**Issue by jukzi** [eclipse-jgit/jgit#17] opened 2024-01-15 14:21 UTC
### Version

latest

### Operating System

Linux/Unix, MacOS, Windows

### Bug description

at the end of each platform build an error is logged

### Actual behavior

exception

### Expected behavior

no exception, load the text while classloader available or inline string "Cleanup during JVM shutdown failed"

### Relevant log output

```Shell
Error: Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/eclipse/jgit/internal/JGitText
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.internal.JGitText
	... 2 more
Error: The process '/Users/runner/hostedtoolcache/maven/3.9.6/x64/bin/mvn' failed with exit code 1
```

### Other information

example: https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/7529302359/job/20493249204?pr=1505)

**Comment by jukzi** [comment] 2024-01-15 14:24
https://github.com/eclipse-jgit/jgit/blob/32e33f0ce8fbd2cdf2abebd1c4651a30770213d4/org.eclipse.jgit/src/org/eclipse/jgit/internal/util/ShutdownHook.java#L85

**Comment by Bananeweizen** [comment] 2024-01-23 08:55
We also see this when trying to upgrade a Tycho 3 build to Tycho 4. Tycho uses JGit in the tycho-buildtimestamp-jgit provider (but I'm not certain whether the failure is that related to that specific usage).

Regarding the bug as such: I'd suggest to hardcode the cleanup failed message here (or to have a try-catch around the localized logging, falling back to hardcoded logging on any exception). Since the VM is shutting down, the JGitText class may or may not be loaded anymore, and that might even depend on the current JVM version or implementation.

**Comment by jukzi** [comment] 2024-02-01 09:22
@msohn can you fix, please?

**Comment by msohn** [comment] 2024-02-06 09:26
pushed fix for review https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1176056

**Comment by msohn** [comment] 2024-02-06 13:34
Fix was merged as e6d83d61eade6dee223757d149a4df9650752a55

**Closed by msohn** 2024-02-06 13:34 UTC

**Comment by LorenzoBettini** [comment] 2024-03-06 11:29
We also see this when trying to upgrade a Tycho 3 build to Tycho 4 in Xtext.
It does not make the build fail but GitHub Actions summaries show failures, though the overall jobs succeed.

@msohn the fix was merged but can we consume the fixed version somehow?

**Comment by msohn** [comment] 2024-03-06 13:43
I tagged the 6.9.0.202403050737-r release and contributed it to the simrel build yesterday.
It's already available on [repo.eclipse.org](https://repo.eclipse.org/content/groups/releases/org/eclipse/jgit/org.eclipse.jgit.repository/6.9.0.202403050737-r/). Will deploy it to Maven central soon.

**Comment by TheSnoozer** [comment] 2024-03-08 15:27
Hello,
thanks for the jgit-project (using it for ages now) could you perhaps let us know when you had the chance to also release the 6.9.0.202403050737-r to maven central? Thanks!

**Comment by msohn** [comment] 2024-03-09 22:06
Yes, technically it's already deployed on Maven Central. We announce the release with Eclipse simultaneous release next Wednesday.

**Comment by henryju** [comment] 2024-04-12 13:46
Hi, after updating to JGit 6.9 to fix the mentioned error, we are now getting:
```text
java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
[09:58:34.514]     	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:143)
[09:58:34.514]     	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
[09:58:34.514]     	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
[09:58:34.514]     	at ch.qos.logback.classic.Logger.error(Logger.java:543)
[09:58:34.514]     	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:87)
[09:58:34.514]     	at java.base/java.lang.Thread.run(Thread.java:840)
[09:58:34.514]     Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
```

is it related?

**Comment by msohn** [comment] 2024-04-13 06:50
JGit uses slf4j API for logging, if you want to use logback as logging backend you need to ensure that its jars are on the classpath

**Comment by henryju** [comment] 2024-04-15 06:57
They are. Everything is working well until the JVM is shutting down. Isn't it the same analysis as the JGitText not found?
> Since the VM is shutting down, the ~JGitText~ ThrowableProxy class may or may not be loaded anymore, and that might even depend on the current JVM version or implementation.

**Comment by henryju** [comment] 2024-04-15 07:10
In our case, we are using JGit in an application that is using classloader isolation. So I guess the problem is that we are closing our classloader before the JGit ShutdownHook is executed.
Relying on a shutdown hook is not good for any scenario involving loading JGit in a child classloader. Would it be possible to make this behavior optional and let people manually call the `cleanup` method before closing their classloaders?

For the record, here is a similar discussion: https://github.com/classgraph/classgraph/issues/376

**Comment by henryju** [comment] 2024-04-25 09:17
Hi folks, would you be open for a change letting clients call the cleanup method themself instead of relying on a shutdown hook?

**Comment by bratwurzt** [comment] 2024-06-17 11:00
Why is this task closed? We are still getting:
```
Exception in thread "Thread-262" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:145)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.error(Logger.java:543)
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:87)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hiddenalpha** [comment] 2024-07-23 08:34
Seems to relate to my case. Error is:
```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:145)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:424)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:386)
	at ch.qos.logback.classic.Logger.error(Logger.java:543)
	at org.eclipse.jgit.internal.util.ShutdownHook.cleanup(ShutdownHook.java:87)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedClassloader.loadClass(IsolatedClassloader.java:82)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more
```

**Comment by jebeaudet** [comment] 2024-07-25 16:33
Most likely related, but ours is on `Stats` : 
```10:41:26  [ERROR] java.lang.NoClassDefFoundError: org/eclipse/jgit/util/Stats
10:41:26  java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/eclipse/jgit/util/Stats
10:41:26      at java.util.concurrent.CompletableFuture.encodeThrowable (CompletableFuture.java:315)
10:41:26      at java.util.concurrent.CompletableFuture.completeThrowable (CompletableFuture.java:320)
10:41:26      at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1770)
10:41:26      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
10:41:26      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
10:41:26      at java.lang.Thread.run (Thread.java:1583)
10:41:26  Caused by: java.lang.NoClassDefFoundError: org/eclipse/jgit/util/Stats
10:41:26      at org.eclipse.jgit.util.FS$FileStoreAttributes.measureMinimalRacyInterval (FS.java:520)
10:41:26      at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$3 (FS.java:442)
10:41:26      at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1768)
10:41:26      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
10:41:26      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
10:41:26      at java.lang.Thread.run (Thread.java:1583)
10:41:26  Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.util.Stats
10:41:26      at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
10:41:26      at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
10:41:26      at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
10:41:26      at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
10:41:26      at org.eclipse.jgit.util.FS$FileStoreAttributes.measureMinimalRacyInterval (FS.java:520)
10:41:26      at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$3 (FS.java:442)
10:41:26      at java.util.concurrent.CompletableFuture$AsyncSupply.run (CompletableFuture.java:1768)
10:41:26      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1144)
10:41:26      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:642)
10:41:26      at java.lang.Thread.run (Thread.java:1583)```

**Comment by TheSnoozer** [comment] 2024-07-25 17:02
I'd recommend to create a new issue if there is still something wrong in the latest version...
